# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)


Sneaker.create(name:"Jordan 4 Retro", price: 250, brand:"Jordan", image_url:"https://stockx-360.imgix.net/Air-Jordan-4-Retro-Bred-2019/Images/Air-Jordan-4-Retro-Bred-2019/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1555622524&w=2200", colorway:"BLACK/FIRE RED-CEMENT GREY-SOLE", description: "These sneakers released in May 2019 and retailed for $200. Thrive in one of Jordan’s most iconic sneakers ever, so make sure you have a pair of your own. Buy them today on HypeStore.")


Sneaker.create(name:"Jordan 6 Retro", price: 300, brand:"Jordan", image_url:"https://stockx-360.imgix.net/Air-Jordan-6-Retro-Black-Infrared-2019/Images/Air-Jordan-6-Retro-Black-Infrared-2019/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1549058088&w=2200", colorway:"BLACK/INFRARED", description: "This AJ6 come with a black upper, black midsole plus red accents, and a translucent sole. These sneakers released in February 2019 and retailed for $200. This silhouette is a must cop, so purchase them on HypeStore now.")


Sneaker.create(name:"Jordan Air 11 Retro", price: 400, brand:"Jordan", image_url:"https://stockx-360.imgix.net/Air-Jordan-11-Retro-Concord-2018/Images/Air-Jordan-11-Retro-Concord-2018/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1551743170&w=2200", colorway:"WHITE/BLACK-CONCORD", description: "This Iconic Jordan 11 colorway is showcasing a white upper with black accents, white midsole, and a freezing cold translucent sole. These sneakers released in December 2018 and retailed for $220. Revisit the dominant legacy MJ left behind and grab a pair on HypStore today.")

Sneaker.create(name:"Sean Wotherspoon Air Max 97", price: 700, brand:"Nike", image_url:"https://stockx-360.imgix.net/Nike-Air-Max-1-97-Sean-Wotherspoon-NA/Images/Nike-Air-Max-1-97-Sean-Wotherspoon-NA/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200", colorway:"LIGHT BLUE FURY/LEMON WAS", description: "Reportedly inspired by Sean’s love for vintage Nike hats from the 1980s, this shoe features both the upper of the Air Max 97 and the sole unit of the Air Max 1, a killer combo. The shoe also has a unique colorful corduroy upper with frayed edges, a truly one-of-a-kind look, with velour from toe to heel. If you’re an Air Max fan, these are a pair that is a must have in your collection and one that will be sure to turn heads. This no accessories version comes with an extra lace set only.")

Sneaker.create(name:"Nike Zoom Rookie Galaxy ", price: 200, brand:"Nike", image_url:"https://stockx-360.imgix.net/Nike-Zoom-Rookie-Galaxy-2019/Images/Nike-Zoom-Rookie-Galaxy-2019/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1551049848&w=2200", colorway:"BLACK/BLACK-ACTION RED", description: "This Zoom Rookie sports a multicolor upper with black accents, white Nike “Swoosh”, black midsole, and a translucent sole. These sneakers released in February 2019 and retailed for $220.")

Sneaker.create(name:"Air Yeezy 2 NRG", price: 3000, brand:"Nike", image_url:"https://stockx-360.imgix.net/Nike-Air-Yeezy-2-NRG-Black-Solar-Red_TruView/Images/Nike-Air-Yeezy-2-NRG-Black-Solar-Red_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200", colorway:"BLACK/BLACK-SOLAR RED", description: "Yeezy bruh...")

Sneaker.create(name:"Yeezy Boost 350 V2", price: 600, brand:"Adidas", image_url:"https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Images/Adidas-Yeezy-Boost-350-V2-Core-Black-Red-2017/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200", colorway:"CORE BLACK/CORE BLACK/RED", description: "Known for their iconic collabs, once again Kanye West and adidas had brewed up more sneaker collection heat with the adidas Yeezy Boost 350 Black Red. Showing 'Pirate Black' flashes, these come with a core black upper and sole that has a core red 'SPLY-350' branding on both sides. These released in November 2016 and retailed at $220.")

Sneaker.create(name:"Yeezy 350 Pirate Black", price: 900, brand:"Adidas", image_url:"https://stockx-360.imgix.net/Adidas-Yeezy-Boost-350-Low-Pirate-Black-2016_TruView/Images/Adidas-Yeezy-Boost-350-Low-Pirate-Black-2016_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1538080256&w=2200", colorway:"PIRATE BLACK/PIRATE BLACK-PIRATE BLACK", description: "The first of it's kind and the first Yeezy to hit the main market. These one of kind Yeezys are a collectible for anyone who has not worn them yet. If you call yourself a true Yeezy fan these are a must have in your collection.")

Sneaker.create(name:"LV Trainer Sneaker Boot", price: 1500, brand:"Louis Vuitton", image_url:"https://stockx.imgix.net/Louis-Vuitton-LV-Trainer-Sneaker-Boot-High-Black-Grey.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1548081350&w=2200", colorway:"BLACK/GREY", description: "Run or climb your way to the top of the ladder with these puppies. Show off how much your feet are worth protecting. Let every one know that you're a hot shot and there's no obstacle that will stand in your way. Grab this pair exclusively at HypeStore")

Sneaker.create(name:"Public Enemy Sk8", price: 500, brand:"Vans", image_url:"https://stockx.imgix.net/Vans-Sk8-Hi-Supreme-Public-Enemy-Black-White.png?fit=fill&bg=FFFFFF&w=700&h=500&auto=format,compress&q=90&trim=color&updated_at=1538080256&w=2200", colorway:"BLACK/WHITE", description: "This 2006 collaboration between Supreme and Vans was inspired by hip-hop group Public Enemy. The Sk8-Hi Sl ‘Supreme Public Enemy’ features a black canvas upper with Public Enemy’s crosshair logo on the side panel bisected by a black leather jazz-stripe. The high-top’s white vulcanized midsole also comes branded with ‘It Takes A Nation of Millions to Hold Us Back,’ the title of the group’s second studio album.")

Sneaker.create(name:"Supreme Skull Pile", price: 300, brand:"Vans", image_url:"https://stockx-360.imgix.net/vans-sk8-hi-supreme-skull-pile-green_TruView/Images/vans-sk8-hi-supreme-skull-pile-green_TruView/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1554255027&w=2200", colorway:"BLACK/GREEN", description: "The Vans Sk8-Hi Supreme Skull Pile Green is a must own pair If you gotta stay fly-y-y-y, y-y, y-y, y. Made in collaboration with Supreme as part of a larger “Skull Pile” Pack, these Vans draw inspiration from Three 6 Mafia’s Juicy J and his infamous green skull tee look from the Stay Fly video. One of three colorways that dropped alongside each other, this pair comes in black and true white, and sports a classic black/white color scheme with a green “skull pile” graphic throughout. Originally dropping in March of 2018, these are a must own for anyone looking to tear da club up.")

Sneaker.create(name:"SB Blazer Frog", price: 240, brand:"Nike", image_url:"https://stockx-360.imgix.net/Nike-SB-Blazer-Frog-Skateboards/Images/Nike-SB-Blazer-Frog-Skateboards/Lv2/img01.jpg?auto=format,compress&q=90&updated_at=1554254260&w=2200", colorway:"LIGHT LIQUID LIME/LAWN-WHITE", description: "If you're feeling froggy then you should cop the Nike SB Blazer Frog Skateboards. This SB Blazer comes with a green upper, green frog, green Nike “Swoosh”, white midsole, and a white sole. These sneakers released in March 2019 and retailed for $95.")
